import { refToVid, vidToRef } from './verse-id';
import { VAV_GRAPH_LIMITS, type VavGraphStats } from './vav-graph-limits';

export type CrossRefEdge = {
  fromVid: number;
  toVid: number;
  votes: number;
  direction: 'out' | 'in';
};

export type CrossRefLookup = {
  outgoing: CrossRefEdge[];
  incoming: CrossRefEdge[];
  maxVotes: number;
};

type TopIndex = Record<string, [number, number][]>;

let outIndex: TopIndex = {};
let inIndex: TopIndex = {};
let meta: {
  maxVotes: number;
  source: string;
  edgeCount: number;
  sourceVerseCount: number;
} | null = null;
let loaded = false;

function ensureLoaded() {
  if (loaded) return;
  try {
    // @ts-ignore — generated by scripts/fetch-cross-references.js
    outIndex = require('../data/cross-refs-out.json');
    // @ts-ignore
    inIndex = require('../data/cross-refs-in.json');
    // @ts-ignore
    meta = require('../data/cross-refs-meta.json');
  } catch {
    outIndex = {};
    inIndex = {};
    meta = null;
  }
  loaded = true;
}

export function isCrossRefDataLoaded(): boolean {
  ensureLoaded();
  return Object.keys(outIndex).length > 0;
}

export function getCrossRefMeta() {
  ensureLoaded();
  return meta;
}

export function lookupCrossRefs(ref: string, minVotes = 0): CrossRefLookup | null {
  ensureLoaded();
  const vid = refToVid(ref);
  if (vid == null) return null;

  const outgoing = (outIndex[String(vid)] ?? [])
    .filter(([, votes]) => votes >= minVotes)
    .map(([toVid, votes]) => ({
      fromVid: vid,
      toVid,
      votes,
      direction: 'out' as const,
    }));

  const incoming = (inIndex[String(vid)] ?? [])
    .filter(([, votes]) => votes >= minVotes)
    .map(([fromVid, votes]) => ({
      fromVid,
      toVid: vid,
      votes,
      direction: 'in' as const,
    }));

  const maxVotes = Math.max(
    0,
    ...outgoing.map((e) => e.votes),
    ...incoming.map((e) => e.votes),
    meta?.maxVotes ?? 0,
  );

  return { outgoing, incoming, maxVotes };
}

function edgesForVid(vid: number, minVotes: number): CrossRefEdge[] {
  const outgoing = (outIndex[String(vid)] ?? [])
    .filter(([, votes]) => votes >= minVotes)
    .map(([toVid, votes]) => ({
      fromVid: vid,
      toVid,
      votes,
      direction: 'out' as const,
    }));

  const incoming = (inIndex[String(vid)] ?? [])
    .filter(([, votes]) => votes >= minVotes)
    .map(([fromVid, votes]) => ({
      fromVid,
      toVid: vid,
      votes,
      direction: 'in' as const,
    }));

  const seen = new Set<string>();
  const edges: CrossRefEdge[] = [];
  for (const edge of [...outgoing, ...incoming]) {
    const key = `${edge.fromVid}-${edge.toVid}`;
    if (seen.has(key)) continue;
    seen.add(key);
    edges.push(edge);
  }
  return edges;
}

export function edgesForGraph(
  ref: string,
  minVotes = 0,
): { centerVid: number; edges: CrossRefEdge[] } | null {
  const layered = edgesForLayeredGraph(ref, minVotes, 1);
  if (!layered) return null;
  return { centerVid: layered.centerVid, edges: layered.edges };
}

function edgeNeighbor(edge: CrossRefEdge, vid: number): number {
  return edge.fromVid === vid ? edge.toVid : edge.fromVid;
}

/** BFS expansion with hard caps — layer 2+ can reach thousands of verses without limits. */
export function edgesForLayeredGraph(
  ref: string,
  minVotes = 0,
  linkLayers = 1,
): { centerVid: number; edges: CrossRefEdge[]; maxVotes: number; stats: VavGraphStats } | null {
  ensureLoaded();
  const centerVid = refToVid(ref);
  if (centerVid == null) return null;

  const {
    maxNodes,
    maxPrimaryEdges,
    maxLinkLayers,
    layer2EdgesPerNode,
    maxFrontierPerLayer,
  } = VAV_GRAPH_LIMITS;

  const layers = Math.max(1, Math.min(maxLinkLayers, linkLayers));
  const seen = new Set<string>();
  const edges: CrossRefEdge[] = [];
  const nodes = new Set<number>([centerVid]);
  let maxVotes = 0;
  let truncated = false;

  const tryAddEdge = (edge: CrossRefEdge): boolean => {
    const key = `${edge.fromVid}-${edge.toVid}`;
    if (seen.has(key)) return false;
    if (edges.length >= maxPrimaryEdges) {
      truncated = true;
      return false;
    }
    seen.add(key);
    edges.push(edge);
    maxVotes = Math.max(maxVotes, edge.votes);
    nodes.add(edge.fromVid);
    nodes.add(edge.toVid);
    return true;
  };

  const centerEdges = edgesForVid(centerVid, minVotes).sort((a, b) => b.votes - a.votes);
  for (const edge of centerEdges) {
    if (edges.length >= maxPrimaryEdges) {
      truncated = true;
      break;
    }
    const neighbor = edgeNeighbor(edge, centerVid);
    if (!nodes.has(neighbor) && nodes.size >= maxNodes) {
      truncated = true;
      continue;
    }
    tryAddEdge(edge);
  }

  let frontier = [...new Set(edges.map((e) => edgeNeighbor(e, centerVid)).filter((v) => v !== centerVid))];

  for (let layer = 2; layer <= layers; layer += 1) {
    if (!frontier.length || nodes.size >= maxNodes || edges.length >= maxPrimaryEdges) break;

    const nextFrontier: number[] = [];
    const sortedFrontier = [...frontier].sort((a, b) => {
      const best = (vid: number) =>
        Math.max(
          ...edgesForVid(vid, minVotes)
            .filter((e) => nodes.has(edgeNeighbor(e, vid)))
            .map((e) => e.votes),
          0,
        );
      return best(b) - best(a);
    });

    for (const vid of sortedFrontier.slice(0, maxFrontierPerLayer)) {
      if (nodes.size >= maxNodes || edges.length >= maxPrimaryEdges) {
        truncated = true;
        break;
      }

      const vidEdges = edgesForVid(vid, minVotes)
        .sort((a, b) => b.votes - a.votes)
        .slice(0, layer2EdgesPerNode);

      for (const edge of vidEdges) {
        if (edges.length >= maxPrimaryEdges) {
          truncated = true;
          break;
        }

        const neighbor = edgeNeighbor(edge, vid);
        const neighborKnown = nodes.has(neighbor);
        if (!neighborKnown && nodes.size >= maxNodes) {
          truncated = true;
          continue;
        }

        const added = tryAddEdge(edge);
        if (added && !neighborKnown) {
          nextFrontier.push(neighbor);
        }
      }
    }

    frontier = nextFrontier;
    if (layer < layers && frontier.length > maxFrontierPerLayer) {
      truncated = true;
    }
  }

  if (linkLayers > maxLinkLayers) truncated = true;

  edges.sort((a, b) => b.votes - a.votes);

  const message = truncated
    ? `Showing up to ${maxNodes} verses and ${maxPrimaryEdges} links. Raise min votes or use fewer layers for a clearer graph.`
    : null;

  return {
    centerVid,
    edges,
    maxVotes: Math.max(maxVotes, meta?.maxVotes ?? 0),
    stats: {
      nodeCount: nodes.size,
      edgeCount: edges.length,
      truncated,
      message,
    },
  };
}

export function formatCrossRefEdge(edge: CrossRefEdge): string {
  return `${vidToRef(edge.fromVid)} → ${vidToRef(edge.toVid)} (${edge.votes})`;
}

/** Direct TSK vote count between two verses (either direction), if present. */
export function getDirectLinkVotes(a: number, b: number): number | null {
  ensureLoaded();
  const out = outIndex[String(a)]?.find(([to]) => to === b)?.[1];
  if (out) return out;
  const incoming = inIndex[String(b)]?.find(([from]) => from === a)?.[1];
  if (incoming) return incoming;
  const reverse = outIndex[String(b)]?.find(([to]) => to === a)?.[1];
  if (reverse) return reverse;
  const reverseIn = inIndex[String(a)]?.find(([from]) => from === b)?.[1];
  return reverseIn ?? null;
}