import { refToVid, vidToRef } from './verse-id';

export type CrossRefEdge = {
  fromVid: number;
  toVid: number;
  votes: number;
  direction: 'out' | 'in';
};

export type CrossRefLookup = {
  outgoing: CrossRefEdge[];
  incoming: CrossRefEdge[];
  maxVotes: number;
};

type TopIndex = Record<string, [number, number][]>;

let outIndex: TopIndex = {};
let inIndex: TopIndex = {};
let meta: {
  maxVotes: number;
  topN: number;
  source: string;
  edgeCount: number;
  sourceVerseCount: number;
} | null = null;
let loaded = false;

function ensureLoaded() {
  if (loaded) return;
  try {
    // @ts-ignore — generated by scripts/fetch-cross-references.js
    outIndex = require('../data/cross-refs-out.json');
    // @ts-ignore
    inIndex = require('../data/cross-refs-in.json');
    // @ts-ignore
    meta = require('../data/cross-refs-meta.json');
  } catch {
    outIndex = {};
    inIndex = {};
    meta = null;
  }
  loaded = true;
}

export function isCrossRefDataLoaded(): boolean {
  ensureLoaded();
  return Object.keys(outIndex).length > 0;
}

export function getCrossRefMeta() {
  ensureLoaded();
  return meta;
}

export function lookupCrossRefs(ref: string, minVotes = 0, limit = 25): CrossRefLookup | null {
  ensureLoaded();
  const vid = refToVid(ref);
  if (vid == null) return null;

  const outgoing = (outIndex[String(vid)] ?? [])
    .filter(([, votes]) => votes >= minVotes)
    .slice(0, limit)
    .map(([toVid, votes]) => ({
      fromVid: vid,
      toVid,
      votes,
      direction: 'out' as const,
    }));

  const incoming = (inIndex[String(vid)] ?? [])
    .filter(([, votes]) => votes >= minVotes)
    .slice(0, limit)
    .map(([fromVid, votes]) => ({
      fromVid,
      toVid: vid,
      votes,
      direction: 'in' as const,
    }));

  const maxVotes = Math.max(
    0,
    ...outgoing.map((e) => e.votes),
    ...incoming.map((e) => e.votes),
    meta?.maxVotes ?? 0,
  );

  return { outgoing, incoming, maxVotes };
}

export function edgesForGraph(
  ref: string,
  minVotes = 0,
  limit = 20,
): { centerVid: number; edges: CrossRefEdge[] } | null {
  const lookup = lookupCrossRefs(ref, minVotes, limit);
  if (!lookup) return null;
  const vid = refToVid(ref);
  if (vid == null) return null;

  const seen = new Set<string>();
  const edges: CrossRefEdge[] = [];

  for (const edge of [...lookup.outgoing, ...lookup.incoming]) {
    const key = `${edge.fromVid}-${edge.toVid}`;
    if (seen.has(key)) continue;
    seen.add(key);
    edges.push(edge);
  }

  edges.sort((a, b) => b.votes - a.votes);
  return { centerVid: vid, edges: edges.slice(0, limit) };
}

export function formatCrossRefEdge(edge: CrossRefEdge): string {
  return `${vidToRef(edge.fromVid)} → ${vidToRef(edge.toVid)} (${edge.votes})`;
}

/** Direct TSK vote count between two verses (either direction), if present. */
export function getDirectLinkVotes(a: number, b: number): number | null {
  ensureLoaded();
  const out = outIndex[String(a)]?.find(([to]) => to === b)?.[1];
  if (out) return out;
  const incoming = inIndex[String(b)]?.find(([from]) => from === a)?.[1];
  if (incoming) return incoming;
  const reverse = outIndex[String(b)]?.find(([to]) => to === a)?.[1];
  if (reverse) return reverse;
  const reverseIn = inIndex[String(a)]?.find(([from]) => from === b)?.[1];
  return reverseIn ?? null;
}