import { buildRef } from '../data/books';

export type RedLetterSegment = {
  text: string;
  isJesus: boolean;
};

export type RedLetterVerse = {
  ref: string;
  segments: RedLetterSegment[];
  greekMask: boolean[];
  kjvMask: boolean[];
};

let redLetterData: Record<string, RedLetterVerse> = {};
try {
  // @ts-ignore — generated by scripts/fetch-red-letter.js
  redLetterData = require('../data/nt-red-letter.json');
} catch {
  /* run npm run data:fetch:red-letter */
}

export function getRedLetterVerse(ref: string): RedLetterVerse | undefined {
  return redLetterData[ref.trim()];
}

export function isJesusGreekWord(ref: string, wordIndex: number): boolean {
  const entry = getRedLetterVerse(ref);
  if (!entry) return false;
  return entry.greekMask[wordIndex] === true;
}

export function isJesusGreekWordById(ref: string, wordId: number): boolean {
  return isJesusGreekWord(ref, wordId - 1);
}

export function getKjvJesusMask(ref: string, wordCount: number): boolean[] {
  const entry = getRedLetterVerse(ref);
  if (!entry) return Array(wordCount).fill(false);
  const mask = entry.kjvMask.slice(0, wordCount);
  while (mask.length < wordCount) mask.push(false);
  return mask;
}

export function tokenizeKjvDisplay(text: string): string[] {
  return text.match(/\S+|\s+/g) ?? [text];
}

export function isRedLetterDataLoaded(): boolean {
  return Object.keys(redLetterData).length > 0;
}

export function getRedLetterRef(book: string, chapter: number, verse: number): string {
  return buildRef(book, chapter, verse);
}