/**
 * New Testament Greek — loaded from MorphGNT SBLGNT Edition (see scripts/fetch-greek-nt.js).
 */

import { parseRef } from './books';
import { getNtBook } from './nt-books';
import { getKjvRows } from './scripture-index';

export type GreekInterlinearWord = {
  id: number;
  greek: string;
  strongs: string;
  transliteration?: string;
  gloss: string;
};

export type GreekScriptureVerse = {
  ref: string;
  book: string;
  chapter: number;
  verse: number;
  kjv: string;
  greek: string;
  words: GreekInterlinearWord[];
  source: string;
};

export const GREEK_NT_SOURCE_ATTRIBUTION =
  'MorphGNT SBLGNT Edition — SBL Greek New Testament text; morphology CC BY-SA 3.0';

let greekNtData: GreekScriptureVerse[] = [];
try {
  // @ts-ignore — generated by scripts/fetch-greek-nt.js
  greekNtData = require('./nt-greek.json');
} catch {
  /* run npm run data:fetch:greek */
}

const greekVerseLookup = new Map<string, GreekScriptureVerse>();
greekNtData.forEach((v) => greekVerseLookup.set(v.ref, v));

export const DEFAULT_KOINE_VERSE: GreekScriptureVerse =
  greekVerseLookup.get('John 1:1') ?? {
    ref: 'John 1:1',
    book: 'John',
    chapter: 1,
    verse: 1,
    source: GREEK_NT_SOURCE_ATTRIBUTION,
    kjv: 'In the beginning was the Word, and the Word was with God, and the Word was God.',
    greek: '',
    words: [],
  };

function getNtKjvText(book: string, chapter: number, verse: number): string {
  const ntBook = getNtBook(book);
  if (!ntBook) return '';
  const row = getKjvRows().find(
    (v) => v.book === ntBook.kjvKey && v.chapter === chapter && v.verse === verse,
  );
  return row?.text ?? '';
}

export function getGreekVerse(ref: string): GreekScriptureVerse | undefined {
  const trimmed = ref.trim();
  const loaded = greekVerseLookup.get(trimmed);
  if (loaded) {
    if (!loaded.kjv) {
      const kjv = getNtKjvText(loaded.book, loaded.chapter, loaded.verse);
      if (kjv) return { ...loaded, kjv };
    }
    return loaded;
  }

  const { book, chapter, verse } = parseRef(trimmed);
  const kjv = getNtKjvText(book, chapter, verse);
  if (!kjv) return undefined;

  return {
    ref: trimmed,
    book,
    chapter,
    verse,
    kjv,
    greek: '',
    words: [],
    source: 'KJV only — Greek not available for this reference',
  };
}

export function getAvailableGreekRefs(): string[] {
  return Array.from(greekVerseLookup.keys());
}

export function getRandomKoineVerseRef(): string {
  const refs = getAvailableGreekRefs().filter((ref) => hasGreekInterlinear(ref));
  if (refs.length === 0) return DEFAULT_KOINE_VERSE.ref;
  return refs[Math.floor(Math.random() * refs.length)];
}

export function hasGreekInterlinear(ref: string): boolean {
  const verse = greekVerseLookup.get(ref.trim());
  return (verse?.words.length ?? 0) > 0;
}

export function isGreekNtDataLoaded(): boolean {
  return greekNtData.length > 0;
}